[[hooks]]
stage = "build"
command = "tailwindcss"
command_arguments = [
    "build",
    "-i",
    "index.css",
    "-o",
    "dist/.stage/tailwind.css"
]

[serve]
address = "127.0.0.1"
port = 1420

[watch]
ignore = ["./src-tauri", "node_modules"]
